concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "Shell-Executor"
  url = "https://gitlab.com"
  id = 23998969
  token = "MY-AWESOME-TOKEN"
  token_obtained_at = 2023-06-03T21:05:13Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"

[[runners]]
  name = "Docker-Executor"
  url = "https://gitlab.com/"
  id = 24011593
  token = "MY-AWESOME-TOKEN"
  token_obtained_at = 2023-06-04T16:16:18Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  cache_dir = "/cache"
  [runners.cache]
    MaxUploadedArchiveSize = 0
  [runners.docker]
    tls_verify = false
    image = "docker:23.0.1"
    # Set Privileget To True to run docker commands in docker image (dind)
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    # for Avoiding to mount Host Docker Daemon socket to gitlab runner 
    # Use Below line and use docker-version-dind in your services in gitlab ci
    # "/etc/docker/daemon.json:/etc/docker/daemon.json:ro"
    volumes = ["/cache","/certs/client", "/etc/docker/daemon.json:/etc/docker/daemon.json:ro"]
    shm_size = 0

